version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    reviewers:
      - "sanksu"
